
# Reusable non-build settings
x-base-service: &base-service
  volumes:
    - ./:/workspace:delegated
    - hf-cache:/workspace/.cache/huggingface

  command: >
    jupyter lab --allow-root
                --ip=0.0.0.0
                --no-browser
                --port=8888
  tty: true
  stdin_open: true
  environment:
    JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    HF_HOME: /workspace/.cache/huggingface
    TRANSFORMERS_CACHE: /workspace/.cache/huggingface
    
  networks:
    - traefik

  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minigpt.rule=Host(`minigpt.${DOMAIN}`)"
    - "traefik.http.routers.minigpt.entrypoints=websecure"
    - "traefik.http.routers.minigpt.tls.certresolver=cloudflare"
    - "traefik.http.services.minigpt.loadbalancer.server.port=8888"
    


# Reusable build fragment
x-base-build: &base-build
  context: .
  dockerfile: Dockerfile

services:
  dev-cpu:
    <<: *base-service
    profiles: ["cpu"]
    build:
      <<: *base-build
      target: runtime-cpu

  dev-cuda:
    <<: *base-service
    profiles: ["cuda"]
    build:
      <<: *base-build
      target: runtime-cuda
    gpus: all

volumes:
  hf-cache:


networks:
  traefik:
    external: true
