# ---------- Build (GPU) ----------
FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime AS build
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_CACHE_DIR=/root/.cache/uv \
    UV_PROJECT_ENVIRONMENT=/usr/local \
    HF_HOME=/workspace/.cache/huggingface \
    TRANSFORMERS_CACHE=/workspace/.cache/huggingface

RUN apt-get update && apt-get install -y --no-install-recommends \
      curl git build-essential tini && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY pyproject.toml uv.lock* ./
RUN --mount=type=cache,target=/root/.cache/uv uv sync
COPY src ./src
# RUN python -m compileall -q src

# ---------- Runtime ----------
FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime AS runtime
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    HF_HOME=/workspace/.cache/huggingface \
    TRANSFORMERS_CACHE=/workspace/.cache/huggingface
RUN apt-get update && apt-get install -y --no-install-recommends tini && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
# COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build /usr/local/ /usr/local/
COPY --from=build /workspace /workspace

RUN mkdir -p .cache/huggingface .jupyter
EXPOSE 8888
ENTRYPOINT ["/usr/bin/tini","--"]
CMD ["jupyter","lab","--ip=0.0.0.0","--no-browser","--port=8888"]
