version: "3.9"

services:
  dev-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: mini-gpt-dev-gpu
    env_file: .env
    volumes:
      - ./:/workspace:delegated
      - hf-cache:${HF_HOME:-/workspace/.cache/huggingface}
    ports:
      - "8888:8888"
    # Modern compose GPU support:
    deploy: # (ignored outside swarm; optional)
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    gpus: all  # Simpler, works in non-swarm recent Docker
    command: >
      sh -c '
        if [ -n "$$JUPYTER_PASSWORD_HASH" ]; then
          jupyter lab --NotebookApp.token= --NotebookApp.password=$$JUPYTER_PASSWORD_HASH --ip=0.0.0.0 --no-browser --port=8888
        else
          jupyter lab --NotebookApp.token=$$JUPYTER_TOKEN --ip=0.0.0.0 --no-browser --port=8888
        fi
      '

volumes:
  hf-cache:
